#!/bin/bash
clear
site=`echo $1 | sed -e "s/\///g"`
type=error
#log format
#  accesslog  : /var/log/apache2/[sitename]/access.[year].[month].[day].log
#  errorlog   : /var/log/apache2/[sitename]/error.[year].[month].[day].log
#  rewritelog : /var/log/apache2/[sitename]/rewrite.[year].[month].[day].log
tail -f /var/log/apache2/*$site*/$type*log

