#!/bin/bash
#log format
#  accesslog  : /var/log/apache2/[sitename].access.log
#  errorlog   : /var/log/apache2/[sitename].error.log
#  rewritelog : /var/log/apache2/[sitename].rewrite.log

site=`echo $1 | sed -e "s/\///g"`
type=error

clear
tail -f /var/log/apache2/*$site**$type*.log
